model:
  anchor_size: 48.0
  image_size: 640
  neck: pafpn
  backbone: resnet18

training:
  batch_size: 32
  max_epoch: 100
  lr: 0.01
  warm_iter: 500
  save_folder: "weights/"
  mutual_guide: iou2classif_weighted

distilling:
  kd: pdf

testing:
  eval_thresh: 0.05
  nms_thresh: 0.5
  vis: False
  seq_matcher: False